name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v2
      - name: Login to DockerHub Registry
        run: docker login -u usernamedocker -p Digi@123 https://useast.jfrog.lexisnexisrisk.com/ui/
      -
        name: Build and push 🐳
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: https://useast.jfrog.lexisnexisrisk.com/artifactory/innuk-dotnetdocker/:latest
