name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      -
        name: Set up QEMU 🏗️
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx 🐋
        uses: docker/setup-buildx-action@v1
      -
        name: Login to JFrog 🐸  
        uses: docker/login-action@v2
        with:
          registry: https://registry-1.docker.io/
          username: usernamedocker
          password: JE2eMeKiKat3LK6Y467NuWWTwcy7tPaLFNbkpb9hq9GWKC1wQy
      -
        name: Build and push 🐳
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: https://useast.jfrog.lexisnexisrisk.com/artifactory/innuk-dotnetdocker/:latest
