name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      -
        name: Set up QEMU 🏗️
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx 🐋
        uses: docker/setup-buildx-action@v1
      -
        name: Login to JFrog 🐸  
        with:
          registry: useast.jfrog.lexisnexisrisk.com
          username: manoharanv@b2b.regn.net
          password: Digi"123
      -
        name: Build and push 🐳
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: https://useast.jfrog.lexisnexisrisk.com/artifactory/innuk-dotnetdocker/:latest
