name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v1
      - name: Login to JFrog Package Registry
        run:  docker login useast.jfrog.lexisnexisrisk.com -u manoharanv@b2b.regn.net --password RGlnaUAxMjM=
      - name: Build the Docker image
        run: docker build -t myimage:latest .
      - name: Tag the Docker image
        run: docker tag myimage:latest useast.jfrog.lexisnexisrisk.com/ui/native/innuk-dotnetdocker/myimage:1.0
      - name: Push the Docker image to the registry
        run: docker push useast.jfrog.lexisnexisrisk.com/ui/native/innuk-dotnetdocker/myimage:1.0
