name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
  
    - name: Login to JFrog Container Registry
      uses: azure/docker-login@v1
      with:
          login-server: https://registry-1.docker.io/
          username: usernamedocker
          password: Welcome@123

 
    - name: Build and Push Docker image to Azure Container Registry
      run: |
           docker build . -t https://registry-1.docker.io/dotnetdocker:${{ github.sha }}
           docker push https://registry-1.docker.io/dotnetdocker:${{ github.sha }}
