name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
  
    - name: Build the Docker image
      run: docker build . -t useast.jfrog.lexisnexisrisk.com/ui/native/innuk-dotnetdocker:${{ github.sha }}
    - name: Login try
      run: docker login -umanoharanv@b2b.regn.net useast.jfrog.lexisnexisrisk.com
      
    - name: Login to JFrog
      uses: docker/login-action@v1
      with:
          registry: useast.jfrog.lexisnexisrisk.com/ui/
          username: manoharanv@b2b.regn.net
          password: Digi@123
    - name: Push the Docker image to the registry
      run: docker push useast.jfrog.lexisnexisrisk.com/ui/native/innuk-dotnetdocker:${{ github.sha }}
