name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
    
      - name: Set up Docker Buildx 🐋
        uses: docker/setup-buildx-action@v1
      -  
        name: Login to JFrog 🐸  
        uses: docker/login-action@v1
        with:
          registry: useast.jfrog.lexisnexisrisk.com/ui/native/innuk-dotnetdocker/
          username: manoharanv@b2b.regn.net
          password: AKCp8nyYHF2oGeYep1SAYLYAaJHFNp8SLgZrL1ghD53c26nDG5Enb7UC1PqVHCB4fXz3FuNZd
      -
        name: Build the Docker image
        run: docker build . -t useast.jfrog.lexisnexisrisk.com/innuk-dotnetdocker/dotnetdocker:${{ github.sha }}
      -
        name: Build and push 🐳   
        uses: jfrog/setup-jfrog-cli@v1
      - run: |
           jfrog rt dp useast.jfrog.lexisnexisrisk.com/innuk-dotnetdocker/dotnetdocker:${{ github.sha }} innuk-dotnetdocker --build-name=docker-build --build-number=1.0.0 --url=https://useast.jfrog.lexisnexisrisk.com/api/docker/innuk-dotnetdocker --user=manoharanv@b2b.regn.net --apikey=AKCp8nyYHF2oGeYep1SAYLYAaJHFNp8SLgZrL1ghD53c26nDG5Enb7UC1PqVHCB4fXz3FuNZd
