name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
  
    - name: Login to JFrog Container Registry
      uses: docker/login-action@v1
      with:
          registry: registry-1.docker.io
          username: usernamedocker
          password: Welcome@123

 
    - name: Build and Push Docker image to JFrog Container Registry
      run: |
           
           docker build . -t registry-1.docker.io/innuk-dotnetdocker:${{ github.sha }}
           docker push registry-1.docker.io/innuk-dotnetdocker:${{ github.sha }}
