name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:dotnetdocker
  
    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
          login-server: appdeeacr.azurecr.io
          username: appdeeacr
          password: T+KPn2IBXjuQsu3c9iJcVFTe4mco63Vx

 
    - name: Push Docker image to Azure Container Registry
      run: |
            docker tag dotnetdocker appdeeacr.azurecr.io/dotnetdocker
            docker push appdeeacr.azurecr.io/dotnetdocker 
