name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login JFrog Docker
      run: docker login -u manoharanv@b2b.regn.net -p AKCp8nyYHF2oGeYep1SAYLYAaJHFNp8SLgZrL1ghD53c26nDG5Enb7UC1PqVHCB4fXz3FuNZd useast.jfrog.lexisnexisrisk.com/ui/native/innuk-dotnetdocker/
    
    - name: Build and push 🐳
      id: docker_build
      uses: docker/build-push-action@v2
      with:
          push: true
          tags: useast.jfrog.lexisnexisrisk.com/ui/native/innuk-dotnetdocker/
