name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
  
  
    - name: Login try
      run: docker login -u manoharanv@b2b.regn.net -p AKCp8nyYHF2oGeYep1SAYLYAaJHFNp8SLgZrL1ghD53c26nDG5Enb7UC1PqVHCB4fXz3FuNZd registry-1.docker.io
    
    - name: Build the Docker image
      run: docker build . -t registry-1.docker.io/innuk-dotnetdocker:dotnetdocker
  
    - name: Push the Docker image to the registry
      run: docker push registry-1.docker.io/innuk-dotnetdocker:dotnetdocker
