name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
    
      - name: Set up Docker Buildx 🐋
        uses: docker/setup-buildx-action@v1
      -  
        name: Login to JFrog 🐸  
        uses: docker/login-action@v1
        with:
          registry: useast.jfrog.lexisnexisrisk.com/ui/native/innuk-dotnetdockerlocal/
          username: manoharanv@b2b.regn.net
          password: AKCp8nyYHF2oGeYep1SAYLYAaJHFNp8SLgZrL1ghD53c26nDG5Enb7UC1PqVHCB4fXz3FuNZd
   
   
      -
        name: Build the Docker image
        run: docker build . -t useast.jfrog.lexisnexisrisk.com/innuk-dotnetdockerlocal/dotnetdocker:${{ github.sha }}
     
     
      -
        name: Push 🐳   
        uses: jfrog/setup-jfrog-cli@v1
      - run: |
           jfrog rt dp useast.jfrog.lexisnexisrisk.com/innuk-dotnetdockerlocal/dotnetdocker:${{ github.sha }} innuk-dotnetdockerlocal --url=useast.jfrog.lexisnexisrisk.com/api/docker/innuk-dotnetdockerlocal/ --user=manoharanv@b2b.regn.net --apikey=AKCp8nyYHF2oGeYep1SAYLYAaJHFNp8SLgZrL1ghD53c26nDG5Enb7UC1PqVHCB4fXz3FuNZd
